// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcdZjjYW9lmsAFHq1zYr0Zjyrji-ppVWQ',
    appId: '1:642686571730:android:15e94fa2bb413031c4c90b',
    messagingSenderId: '642686571730',
    projectId: 'app-110-policy',
    storageBucket: 'app-110-policy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL6ZnCOkUbnbiZ3gj3qo9soVSa3SZB4mQ',
    appId: '1:642686571730:ios:0f0b1559dd410ad4c4c90b',
    messagingSenderId: '642686571730',
    projectId: 'app-110-policy',
    storageBucket: 'app-110-policy.firebasestorage.app',
    iosClientId:
        '642686571730-ruig7mo95g9rg67u8unfckvirj6s6rnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
